services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: esr_sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:

# ATT
